server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    host: 192.168.2.182
    username: postgres
    password: msdnmm
    dbname: postgres
    port: 5432
    ssl_mode: disable
    time_zone: Asia/Shanghai

  redis:
    user: master1
    pass: "263393"
    addr: 192.168.2.102:6379
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
trace:
#  endpoint: http://192.168.2.100:30188/api/traces
  endpoint: 192.168.2.152:30507
